### ISSUE TITLE
Some technical questions

### ISSUE THREAD

**Issue by Cogito2012** [telegie/pyrgbd#1]
Hi,

Thank you for sharing the source code! This is really helpful for me to conduct research with 3D vision data from iPhone. I have a few technical questions here:

 - Is it possible to read the **camera intrinsics** from the telegie app? Though the RGB and depth frames could be decoded by your `main.py`, we still found it hard to find the raw camera intrinsics for a specific iPhone such as iPhone 13 Pro, and not sure if the decoded RGB-D frames corresponds to the raw camera intrinsics or not.
 - What are the "Direction X" and "Direction X Diff Delta" which are visualized by the `main.py`?

Looking forward to your reply. Thank you in advance!

**Comment by hanseuljun** [comment]
Hello!

Thanks for your interest in our newly open-sourced project. We hope you document things more, but for now, due to immense lack of human power, we skipped many many parts in terms of commenting and documenting and it is impressive you figured out this much.

I think I can answer your questions together:
Directions are vectors that correspond to each pixels of the depth frame that can be used to convert the depth values of the pixels into points. In other words,

v_{i, j} = direction_{i, j} * d_{i, j}
when v_{i, j}:= point corresponding to pixel (i, j)
direction_{i, j}:= direction value of pixel (i, j)
d_{i, j}:= depth value of pixel (i, j)

Given the camera intrinsics are usually needed for this 2D to 3D conversion these direction values do, we haven't exposed the camera intrinsics to the python API (yet). In case you need to know the camera intrinsics, let me know!

The decoded RGB-D frames do correspond to the camera intrinsics when both "frames" and "calibration" come from the same File instance.

**Comment by Cogito2012** [comment]
Thanks for the prompt and detailed reply! 
Can I interpret the points v_{i,j} as 3D point cloud? In this case, is the traditional pinhole camera model still applicable here? If yes, I guess the camera intrinsics should be known, right?

With the camera intrinsics and pinhole model, the 2D pixel location {i,j} and 3D physical location (x,y,z) can be mutually converted, which will be very convenient in practice.

Thus, we appreciate it if you could expose the camera intrinsics by python API. For the depth meanings, I believe it is sufficient for practical usage with the current meaning of 1 mm for depth value 1.

**Comment by Cogito2012** [comment]
To my understanding, if it is a pinhole model, we can indeed do the conversion from 2D location (u,v) to 3D point (X, Y, Z) by leveraging `[X, Y, Z] = [(u - ox) / fx, (v - oy) / fy, 1] * depth[u,v]`.  

So if the directions are provided, we can do the **2D-to-3D** conversion like this without access to the intrinsics:

 *Given 2D pixel location (u,v), the direction dir=direction[u, v]:= (a, b, c), then the 3D location [X, Y, Z] = [a/c, b/c, 1] * depth[u, v]*

However, the **3D-to-2D** conversion seems to be infeasible without knowing the intrinsics, right? Correct me if I made mistakes:)

**Comment by hanseuljun** [comment]
Unfortunately, the camera model is not a simple pinhole model, but a pinhole model with lens distortion. This makes conversion more complicated than a single matrix multiplication. See below for the C++ implementation of this conversion. It is function compute_ios_direction():

https://github.com/telegie/librgbd/blob/40420b14d18e67c76ba831d7c770ccd151fbb701/src/ios_calibration_utils.cpp

Lens distortion makes the inversion conversion, which is 3D-to-2D, even more complicated.

In brief, I would recommend relying on the direction values than trying to implement 2D-to-3D conversion by yourself, unless it is a must for your use case.

And the 3D location would be, using the notation you have provided in the latest comment
[X, Y, Z] = [a, b, c] * depth[u, v]

Don't divide it by c, and in most cases, c will be -1. It is -1 since librgbd is based on a right-hand coordinate system that +x is right, +y up, and +z is backwards.

**Comment by Cogito2012** [comment]
@hanseuljun That make sense. 

Another question, is it possible to transform the per-frame 3D points into the same referenced coordinate system when the iPhone was moving? With lens distortion, I'm not clear how complicated such transformation will be.

**Comment by hanseuljun** [comment]
In brief, yes. The requirement would be figuring how much the camera moved.

In details, let's say their is points_{t1} and points_{t2}, which are points corresponding to the frame captured at t1 and t2. After converting 2D depth frames into 3D points, there is nothing to do with lens distortion. You only need to figure out the amount of translation and rotation happened to the phone between t1 and t2.

For figuring out the amount of translation and rotation, one way is to use ICP (iterative closest point). This approach only requires points_{t1} and points_{t2} to figure out the translation and rotation between t1 and t2.

While I hope ICP to be enough for your use case, a more advanced way would require IMU (especially the gyroscope) data from the phone. They are actually included in the .mkv files from Telegie. Unfortunately, while I tried to write code correctly, IMU data hasn't been really tested. That is on my TODO list and would happen, if I stick to my plan, in less than a month.
